# Kbuild file for out-of-tree driver only !!!DO NOT PUSH UPSTREAM!!!
include $(src)/Makefile
intel_qat-objs += ../../../../compat/qat_compat.o \
	qat_algs_old.o \
	qat_asym_algs_old.o \

intel_qat-$(QAT_UIO) += \
	adf_uio.o \
	adf_uio_control.o \
	adf_uio_cleanup.o \
	adf_dev_processes.o \
	qdm.o

ccflags-$(QAT_UIO) += -DQAT_UIO=y -DQAT_RSA_SUPPORT=y -DQAT_AEAD_OLD_SUPPORT=y \
	-DDEFER_UPSTREAM=y
ifdef KPT
intel_qat-$(QAT_UIO) += adf_mei_kpt.o
ccflags-$(QAT_UIO) += -DKPT=y
endif

