#
# Copyright 2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ddr.o
obj-y += gpio.o
obj-y += sn74lv164a.o
obj-y += led.o
ifndef CONFIG_SPL_BUILD
obj-y += eth.o
endif
obj-y += ls1043aqds.o
