sudo: required
language: c
services:
  - docker

compiler:
  - gcc
  - clang

env:
  - DOCKER_IMAGE=ubuntu-18.04
  - DOCKER_IMAGE=ubuntu-20.04
  - DOCKER_IMAGE=fedora-30
  - DOCKER_IMAGE=opensuse-leap
  - DOCKER_IMAGE=ubuntu-18.04 TPM2_TSS_VERSION=master

# only one build should:
#  - report coverage stats
#  - report coverity scan info (branch coverity_scan only)
matrix:
  include:
  - env: ENABLE_COVERAGE=true DOCKER_IMAGE=ubuntu-18.04
    compiler: gcc
  - env: ENABLE_COVERITY=true DOCKER_IMAGE=ubuntu-18.04
    compiler: gcc
script:
  - ./.ci/travis.run

after_failure:
  - cat build/test-suite.log
