#
# Makefile for pssBspApis mv_KernelExt mvPpDrv modules
#

obj-$(CONFIG_WG_PLATFORM_MODULES)	+= wg_pss.o
obj-$(CONFIG_WG_PLATFORM_MODULES)	+= pssBspApis.o
obj-$(CONFIG_WG_PLATFORM_MODULES)	+= mvPpDrv/
obj-$(CONFIG_WG_PLATFORM_MODULES)	+= mv_KernelExt/
